checks:
  php: true
filter:
  paths:
    - 'src/*'
  dependency_paths:
    - 'vendor/*'

build:
  image: default-jammy
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
