# AddPlaceholderRelation migration
---

create:
  relations:
    - name: placeholder
      label: Placeholder
      inverse_name: placeholded
      inverse_label: Placeholded in
      description: Relation to link objects with other objects that appear in the body of the former.
      left:
        - objects
      right:
        - media
